### ISSUE TITLE
image ids of coco

### ISSUE THREAD

**Issue by mathschy** [ivendrov/order-embedding#1]
Hi
It seems the coco.zip file from http://www.cs.toronto.edu/~vendrov/order/coco.zip doesn't contain the ids of images, but only the features and the captions.
Is there a way to recover the image id ? (I would like to display images of training set, instead of captions)
Thanks
Best

**Comment by ivendrov** [comment]
Horribly late reply, but for anyone else who has the same question: when you expand the models.zip file, `vis/roc/coco/image_urls.json` has the image permalinks in order. That's what the visualization server uses to display images.
