### ISSUE TITLE
Training not working

### ISSUE THREAD

**Issue by VAIBHAV-2303** [ivendrov/order-embedding#6]
TypeError: ('An update must have the same type as the original shared variable (shared_var=<TensorType(float32, matrix)>, shared_var.type=TensorType(float32, matrix), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

I am getting this error upon running `python2 driver.py order`
I am not used to theano, can someone please point out how to fix this. I have used theano 0.7.

**Comment by hunain-saeed** [comment]
Hello Mr Vaibhav I am facing the same issue can you tell me how you solved it. @VAIBHAV-2303
